id = "toml"
name = "TOML"
version = "0.1.3"
schema_version = 1
description = "TOML support."
repository = "https://github.com/zed-industries/zed"
authors = ["Max Brunsfeld <max@zed.dev>", "Ammar Arif <evergreenkary@gmail.com>"]
themes = []
icon_themes = []
languages = ["languages/toml"]

[lib]
kind = "Rust"
version = "0.1.0"

[grammars.toml]
repository = "https://github.com/tree-sitter/tree-sitter-toml"
rev = "342d9be207c2dba869b9967124c679b5e6fd0ebe"

[language_servers.taplo]
language = "TOML"
languages = []

[language_servers.taplo.language_ids]

[context_servers]

[slash_commands]

[indexed_docs_providers]
