id = "env"
name = "env"
version = "0.0.1"
schema_version = 1
description = "ğŸ” Environment support. âœ° and report issues â©"
repository = "https://github.com/zarifpour/zed-env"
authors = ["Daniel Zarifpour <z@rifpour.xyz>"]
themes = []
languages = ["languages/env"]

[lib]

[grammars.env]
repository = "https://github.com/zarifpour/tree-sitter-dotenv"
rev = "a854096808a5c1da0de998b31e5887995a98a89f"

[language_servers]

[slash_commands]
